<a href="https://colab.research.google.com/github/TiSha32/150-days-of-machine-learning/blob/main/Day-002/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore')

# Dataset - https://drive.google.com/file/d/1HqTcjEjTTb9-4o6RezlY3BHwHFeQdbn9/view?usp=sharing

In [11]:
df = pd.read_csv('/content/drive/MyDrive/Housing.csv')
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [12]:
cat_cols = [cols for cols in df.columns if df[cols].dtype == 'O']

In [13]:
cat_cols

['mainroad',
 'guestroom',
 'basement',
 'hotwaterheating',
 'airconditioning',
 'prefarea',
 'furnishingstatus']

In [14]:
sk_encoder = OneHotEncoder(sparse_output = False, drop = 'first', dtype = 'i2')
sk_encoded = sk_encoder.fit_transform(df[cat_cols])
sk_encoded_df = pd.DataFrame(sk_encoded, columns = sk_encoder.get_feature_names_out())

In [15]:
sk_encoded_df.head()

,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,1,0,0,0,1,1,0,0
1,1,0,0,0,1,0,0,0
2,1,0,1,0,0,1,1,0
3,1,0,1,0,1,1,0,0
4,1,1,1,0,1,0,0,0

In [16]:
sk_encoded_df = pd.concat([df.drop(cat_cols,axis = 1),sk_encoded_df], axis = 1)

In [17]:
sk_encoded_df.head()

,price,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,4,3,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,2,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,2,3,1,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,1,1,1,0,1,0,0,0

In [20]:
#Get dummies (Don't use because of data leak)
pd.get_dummies(df, drop_first = True, dtype = 'i2')

,price,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,4,3,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,2,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,2,3,1,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,1,1,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,2,1,0,1,0,0,0,0,1
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1,0
542,1750000,3620,2,1,1,0,1,0,0,0,0,0,0,1
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,0,1,0,0,0,0,0,0,1

In [21]:
sk_encoded_df.columns = sk_encoded_df.columns.str.replace('_yes','')
sk_encoded_df.columns = sk_encoded_df.columns.str.replace('furnishingstatus_','')

In [22]:
sk_encoded_df.head()

,price,area,bedrooms,bathrooms,stories,parking,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,semi-furnished,unfurnished
0,13300000,7420,4,2,3,2,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,4,3,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,2,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,2,3,1,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,1,1,1,0,1,0,0,0

In [29]:
#Train test split
x = sk_encoded_df.drop(['price'], axis = 1)
y = sk_encoded_df['price']
x_train, x_split, y_train, y_split = train_test_split(x, y, test_size = 0.3, random_state = 42)
x_train.head()

,area,bedrooms,bathrooms,stories,parking,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,semi-furnished,unfurnished
126,7160,3,1,1,2,1,0,1,0,0,1,0,1
363,3584,2,1,1,0,1,0,0,1,0,0,1,0
370,4280,2,1,1,2,1,0,0,0,1,0,1,0
31,7000,3,1,4,2,1,0,0,0,1,0,1,0
113,9620,3,1,1,2,1,0,1,0,0,1,0,0

# Data Leak prevention

In [3]:
data = pd.read_csv('/content/drive/MyDrive/Housing.csv')
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [5]:
pd.DataFrame({'Missing_values' : data.isnull().sum(),
             'Data_Types' : data.dtypes})

                  Missing_values Data_Types
price                          0      int64
area                           0      int64
bedrooms                       0      int64
bathrooms                      0      int64
stories                        0      int64
mainroad                       0     object
guestroom                      0     object
basement                       0     object
hotwaterheating                0     object
airconditioning                0     object
parking                        0      int64
prefarea                       0     object
furnishingstatus               0     object

In [9]:
#dependency split
x = data.iloc[:,1:]
y = data.iloc[:,0]

In [13]:
#train test split
x_train,x_test, y_train,y_test = train_test_split(x,y, random_state = 42, test_size = 0.3)

In [17]:
# x_train sample
x_train.head()
#print(f'Shape of x_train: {x_train.shape}, Shape of x_test: {x_test.shape}')

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
126,7160,3,1,1,yes,no,yes,no,no,2,yes,unfurnished
363,3584,2,1,1,yes,no,no,yes,no,0,no,semi-furnished
370,4280,2,1,1,yes,no,no,no,yes,2,no,semi-furnished
31,7000,3,1,4,yes,no,no,no,yes,2,no,semi-furnished
113,9620,3,1,1,yes,no,yes,no,no,2,yes,furnished

In [25]:
#train test encoding


#train encoding
encoder = OneHotEncoder(sparse_output = False, dtype = 'i2', drop = 'first')
cat_cols = [cols for cols in x_train.columns if x_train[cols].dtype == 'O']
x_train_cat_encoded = encoder.fit_transform(x_train[cat_cols])
x_train_cat_df = pd.DataFrame(x_train_cat_encoded, index = x_train.index, columns = encoder.get_feature_names_out())
x_train_encoded = pd.concat([x_train_cat_df, x_train.drop(cat_cols, axis = 1)], axis = 1)
x_train_encoded.head()


#test encoding

x_test_cat_encoded = encoder.transform(x_test[cat_cols])
x_test_cat_df = pd.DataFrame(x_test_cat_encoded, index = x_test.index, columns = encoder.get_feature_names_out())
x_test_encoded = pd.concat([x_test_cat_df, x_test.drop(cat_cols, axis = 1)], axis = 1)
x_test_encoded.head()

,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished,area,bedrooms,bathrooms,stories,parking
316,0,0,1,0,0,0,0,1,5900,4,2,2,1
77,1,0,0,0,1,1,0,0,6500,3,2,3,0
360,1,0,0,0,0,0,1,0,4040,2,1,1,0
90,1,0,0,0,1,0,1,0,5000,3,1,2,0
493,1,0,0,0,0,0,0,0,3960,3,1,1,0

In [36]:
# train test scaling

scaled = StandardScaler()
x_train_scaled = scaled.fit_transform(x_train_encoded)
x_train_scaled_df = pd.DataFrame(x_train_scaled, index = x_train_encoded.index, columns = scaled.get_feature_names_out())
x_train_scaled_df.head()

x_test_scaled = scaled.fit_transform(x_test_encoded)
x_test_scaled_df = pd.DataFrame(x_test_scaled, index = x_test_encoded.index, columns = scaled.get_feature_names_out())
round(x_test_scaled_df.describe(),2)

,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished,area,bedrooms,bathrooms,stories,parking
count,164.00,164.00,164.00,164.00,164.00,164.00,164.00,164.00,164.00,164.00,164.00,164.00,164.00
mean,0.00,-0.00,-0.00,-0.00,-0.00,-0.00,-0.00,-0.00,-0.00,-0.00,-0.00,-0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-2.36,-0.43,-0.70,-0.18,-0.67,-0.55,-0.80,-0.76,-1.63,-1.40,-0.61,-0.98,-0.82
25%,0.42,-0.43,-0.70,-0.18,-0.67,-0.55,-0.80,-0.76,-0.79,0.03,-0.61,-0.98,-0.82
50%,0.42,-0.43,-0.70,-0.18,-0.67,-0.55,-0.80,-0.76,-0.10,0.03,-0.61,0.16,-0.82
75%,0.42,-0.43,1.43,-0.18,1.49,-0.55,1.25,1.32,0.58,0.03,1.18,0.16,0.55
max,0.42,2.30,1.43,5.64,1.49,1.82,1.25,1.32,3.72,4.30,2.98,2.44,2.46